config/routes.rb
Rails.application.routes.draw do
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  STATUSES = %w[waiting in_progress ended].freeze
  validates :name, :description, :status, presence: true
  validates :status, inclusion: { in: STATUSES }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Create successful.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end
  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:name, :description, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kr1Rails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Редагування завдання</h1>

<%= form_with(model: @task, local: true) do |form| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "Error") %> в формі:</h2>

      <ul>
        <% @task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status, Task::STATUSES %>
  </div>

  <div class="actions">
    <%= form.submit "Save" %>
  </div>
<% end %>

<%= link_to 'Back to tasks list', tasks_path %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>State</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @tasks.each do |task| %>
    <tr bgcolor="#2f4f4f">
      <td><%= task.name %></td>
      <td><%= task.description %></td>
      <td><%= task.status %></td>
      <td><%= link_to 'Check', task %></td>
      <td><%= link_to 'Redact', edit_task_path(task) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Create new task', new_task_path %>

app/views/tasks/new.html.erb
<h1>Створення нового завдання</h1>

<%= form_with(model: @task, local: true) do |form| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "Error") %> в формі:</h2>

      <ul>
        <% @task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status, Task::STATUSES %>
  </div>

  <div class="actions">
    <%= form.submit "Save" %>
  </div>
<% end %>

<%= link_to 'Back to tasks list', tasks_path %>

app/views/tasks/show.html.erb
<h1><%= @task.name %></h1>

<p>
  <strong>Опис:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Статус:</strong>
  <%= @task.status %>
</p>

<%= link_to 'Redact', edit_task_path(@task) %> |
<%= link_to 'Back to tasks list', tasks_path %>